### POST create patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@email.com",
  "address": "St.Address 12345",
  "dateOfBirth": "1995-01-02",
  "registeredDate": "2001-01-01"
}

###